config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'quotes/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'welcome#index'
  
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  get '/contact', to: 'contact#index'
  get '/services', to: 'services#index'

  get '/quote', to: 'quotes#index'
  post '/quote', to: 'quotes#create'

  get '/submitted', to: 'submits#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :info, :error, :warning
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def create
      @quote = Quote.new
      @quote.name = params[:name]
      @quote.address_1 = params[:address_1]
      @quote.address_2 = params[:address_2]
      @quote.move_date = params[:move_date]
      @quote.phone = params[:phone]
      @quote.user_id = current_user.id
      if @quote.save
        redirect_to '/submitted', notice: "Your quote has been submitted!"
      else
        redirect_to root_path, alert: "Required field missing"
      end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    def index
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        @user = User.find_by(username: params[:username])
        #authenticate user credentials
        if !!@user && @user.authenticate(params[:password])
            #set session and redirect on success
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            #error message on fail
            message = "Something went wrong! Make sure your username and password are correct"
            redirect_to login_path, notice: message
        end
    end
end

app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
    def index
        @quote = Quote.last
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
    end

    def active_class(path)
        if request.path == path
          return 'active'
        else
          return ''
        end
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/submits_helper.rb
module SubmitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/index.html.erb
<h1>Contact Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Primary Meta Tags -->
  <title>Affordable Moving Services Columbus, Ohio | Moving General</title>
  <meta name="title" content="Affordable Moving Services Columbus, Ohio | Moving General">
  <meta name="description" content="Moving General offers Packing, Loading, Unloading, Junk Removal, and Full-Service Moves. We set the standard when It Comes to Moving. ">
  
  <!-- Open Graph / Facebook -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://movinggeneral.com/">
  <meta property="og:title" content="Affordable Moving Services Columbus, Ohio | Moving General">
  <meta property="og:description" content="Moving General offers Packing, Loading, Unloading, Junk Removal, and Full-Service Moves. We set the standard when It Comes to Moving. ">
  <meta property="og:image" content="https://movinggeneral.com/assets/icon-c6c17cf42bf5dd7ce7690aca3363695a6966fe25acb4be0b5246fdeab68b3ebe.PNG">
  
  <!-- Twitter -->
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:url" content="https://movinggeneral.com/">
  <meta property="twitter:title" content="Affordable Moving Services Columbus, Ohio | Moving General">
  <meta property="twitter:description" content="Moving General offers Packing, Loading, Unloading, Junk Removal, and Full-Service Moves. We set the standard when It Comes to Moving. ">
  <meta property="twitter:image" content="https://movinggeneral.com/assets/icon-c6c17cf42bf5dd7ce7690aca3363695a6966fe25acb4be0b5246fdeab68b3ebe.PNG">    
  <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon (1).ico') %>

    <!-- Schema -->

    <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "MovingCompany",
  "name": "Moving General LLC",
  "image": "https://movinggeneral.com/assets/icon-c6c17cf42bf5dd7ce7690aca3363695a6966fe25acb4be0b5246fdeab68b3ebe.PNG",
  "@id": "",
  "url": "https://movinggeneral.com/",
  "telephone": "+1-614-398-1565",
  "priceRange": "$$",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "",
    "addressLocality": "Columbus",
    "addressRegion": "OH",
    "postalCode": "43212",
    "addressCountry": "US"
  } ,
  "sameAs": [
    "https://www.facebook.com/movinggeneral88",
    "https://www.instagram.com/movinggeneral88/",
    "https://www.linkedin.com/company/moving-general-llc/"
  ] 
}
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-E37RM6L9K0"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-E37RM6L9K0');
</script>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <% unless request.path == "/submitted" %>
      <div class="nav-menu">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <div class="navbar">
            <a class="<%= active_class(root_path) %>" href="/"><i class="fa fa-fw fa-home"></i> Home</a>
            <a class="<%= active_class(services_path) %>" href="/services"><i class="fa fa-fw fa-users"></i> Services</a>
            <a class="<%= active_class(quote_path) %>" href="/quote"><i class="fa fa-fw fa-envelope"></i> Book Now!</a>
            <!--
                <a href="/users/sign_up"><i class="fa fa-fw fa-user"></i>
                    <% if !logged_in? %> 
                        Login
                    <% else %>
                        <%= current_user.username %>
                    <% end %>
                </a>
            -->
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/quotes/index.html.erb
<div id="quote-page">
    <div id="quote-container">
        <h1 id="quote-title">&bull; Quote &bull;</h1>
        <div class="underline">
        </div>
        <div class="icon-wrapper">
            <%= image_tag("icon.PNG", class: "quote-icon") %>
        </div>
        <%= form_with url: "/quote", method: :post do |form| %>
            <%= form.text_field :name, required: true, placeholder: "Name" %>
            <br>
            <%= form.telephone_field :phone, required: true, placeholder: "515-098-1234" %>
            <br>
            <%= form.text_field :address_1, required: true, placeholder: "Current Address" %>
            <br>
            <%= form.text_field :address_2, required: true, placeholder: "Destination Address" %>
            <br>
            <%= form.date_field :move_date, required: true %>
            <br>
            <%= form.submit "Get your Quote!", id: "form_button" %>
        <% end %>
    </div>
</div>

app/views/services/index.html.erb
<head>

</head>

<body class="services">


    <div class="container" id="title_container">
        <h1 class="services_title">We Take Pride In Your Move</h1>
    </div>

    <div class="container" id="service_container">
        <div class="flex-grid">
            <br><br>
            <div class="col" id="box_1">
                <%= image_tag("package (2).png", class: "icon-img") %>
                <h3>Packing</h3>
                <p>We will box all of your loose items.</p>
            </div>
            <div class="col" id="box_2">
                <%= image_tag("loading (1).png", class: "icon-img") %>
                <h3>Loading/Unloading</h3>
                <p>We handle all your labor service needs.</p>
            </div>
            <div class="col" id="box_3">
                <%= image_tag("trash (3).png", class: "icon-img") %>
                <h3>Trash Removal</h3>
                <p>Big or small, you know the Moving General has your haul!</p>
            </div>
        </div>
        <br><br>
        <div class="button_slide slide_left"><a href="/quote">Free Quote</a></div>
        <br><br>
    </div>

</body>

<footer>
    <div class="container" id="footer_container">
        <%= image_tag("icon.PNG", class: "icon") %>
        <div class="flex-grid-footer">
            <div class="col">
                <a href="#"><h5>HOME</h5></a>
            </div>
            <div class="col">
                <a href="/services"><h5>SERVICES</h5></a>
            </div>
            <div class="col">
                <a href="/contact-us"><h5>CONTACT</h5></a>
            </div>
        </div>
        <p>Feel Free to Contact Us at Any Time to Ask a Question or Chat!</p>
        <p>alex@movinggeneral.com</p>
        <p>cole@movinggeneral.com</p>
        <h3 id="phone_number"><a href="tel:6143981565">614-398-1565</a></h3>
        <div class="flex-grid-footer">
            <div class="col">
                <a href="https://www.facebook.com/movinggeneral88"><%= image_tag("f_logo_RGB-White_72.png", class: "icon") %></a>
            </div>
            <div class="col">
                <a href="https://www.instagram.com/movinggeneral88"><%= image_tag("instagram-icon-white.png", class: "icon") %></div></a>
            <div class="col">
                <a href="https://www.linkedin.com/company/moving-general-llc/"><%= image_tag("In-White-121px-R.png", class: "icon") %></a>
            </div>
        </div>
        <p class="site-footer__fineprint" id="fineprint">Copyright ©2021 | Moving General LLC | All Rights Reserved</p>
    </div>
</footer>

app/views/submits/index.html.erb
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">
	<link href='https://fonts.googleapis.com/css?family=Lato:300,400|Montserrat:700' rel='stylesheet' type='text/css'>
	<style>
		@import url(//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css);
		@import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);
	</style>
	<link rel="stylesheet" href="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/default_thank_you.css">
	<script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/jquery-1.9.1.min.js"></script>
	<script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/html5shiv.js"></script>
</head>
<body class="submit">
    <div class="submit-container">
        <header class="site-header" id="header">
            <h1 class="submitted-title" data-lead-id="site-header-title">THANKS <%= @quote.name %>!</h1>
        </header>

        <div class="main-content">
            <i class="fa fa-check main-content__checkmark" id="checkmark"></i>
            <p class="main-content__body" data-lead-id="main-content-body">Thanks for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. A member of our team will reach out shortly.</p>
        </div>
        <br><br>
        <div class="button_slide slide_left"><a id="home-button" href="/">Home</a></div>
    </div>

	<footer class="site-footer" id="footer">
		<p class="site-footer__fineprint" id="fineprint">Copyright ©2021 | Moving General LLC | All Rights Reserved</p>
	</footer>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <% stylesheet_link_tag "application", :media => "all" %>
    <% stylesheet_link_tag params[:controller] %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">
</head>

<body class="<%= controller.controller_name%>">
  <title>
    <div class="header">
        <h1>Moving General</h1>
    <div>
  </title>

    <div class="container" id="main_container">
        
        <h1 id="title_text">Moving General</h1>
        <h3 id="phone_number"><a href="tel:6143981565">614-398-1565</a></h3>
        <%= image_tag("icon.PNG", class: "icon", alt: "Moving General llc") %>
        <h3 id="dot_number">USDOT# 3625861</h3>  
        <br><br><br><br>
        <<div class="button_slide slide_left"><a href="/quote">Free Quote</a></div>
        <br><br><br><br>
        <div>
            <p class="title1">WE OFFER PACKING, LOADING, UNLOADING, JUNK REMOVAL, AND FULL
            SERVICE MOVES. WE SET THE STANDARD WHEN IT COMES TO
            MOVING. WE KNOW YOU'LL BE IN GOOD HANDS</p>
        </div>
        <br><br>
    </div>
    
    <div class="container" id="services_container">
        <br>
        <h1>There Are Just a Few Things
        That We Can Do Very Well.</h1>
        <br><br><br>
        <div class="flex-grid">
            <div class="col" id="box_1">
                <%= image_tag("package (2).png", class: "icon-img") %>
                <h3>Packing</h3>
                <p>We will box all of your loose items.</p>
            </div>
            <div class="col" id="box_2">
                <%= image_tag("loading (1).png", class: "icon-img") %>
                <h3>Loading/Unloading</h3>
                <p>We handle all your labor service needs.</p>
            </div>
            <div class="col" id="box_3">
                <%= image_tag("trash (3).png", class: "icon-img") %>
                <h3>Trash Removal</h3>
                <p>Big or small, you know the Moving General has your haul!</p>
            </div>
        </div>
        <br><br>
        <div class="button_slide slide_left"><a href="/services">View all our Services</a></div>
    </div>

    <div class="container" id="about_container">
        <br><br><br>
        <div class="about-grid">
            <div class="col" id="about-left">
                <%= image_tag("ben-allied.jpg", class: "crew") %>
            </div>
            <div class="col">
                <h5>Who We Are</h5><br>
                <h2>About Us.</h2><br>
                <%= image_tag("ben-allied.jpg", id: "ben-allied") %>
                <p>We are the Moving General. Our company is built on three pillars: 
                Trust, Simplicity, and Professionalism. We look to build and exceptional 
                relationship with you, get the job done, and keep things
                simple in whatever we do.</p><br>
                

            </div>
        </div>
    </div>

    <div class="container" id="testimonial_container">
        <div class="testimonial-grid">
            <div class="col">
                <h5>Client Testimonial</h5>
                <h2>Some Positive Feedback That Encourages Us.</h2><br>
                <%= image_tag("customer.jpg", id: "customer") %>
                <p>"These two guys are seriously AMAZING. I cannot say enough kind words 
                about them. They made my move from Pittsburgh to Cincinnati so much less stressful.
                They took care of all of our belongings like they were their own, and I cannot 
                appreciate that enough!!! They were also really fun to talk to and be around. 
                I cannot recommend a better moving crew!!! Thank you so much, guys!!!!!"</p>
                <h6>~Kandace M<h6>
            </div>
            <div class="col">
                    <%= image_tag("customer.jpg", id: "testimonial") %>
            </div>
        </div>
    </div>
    
    <footer id="footer">
        <div class="container" id="footer_container">
            <div class="flex-grid-footer">
                <div class="col">
                    <a href="/"><h5>HOME</h5></a>
                </div>
                <div class="col">
                    <a href="/services"><h5>SERVICES</h5></a>
                </div>
                <div class="col">
                    <a href="/quote"><h5>CONTACT</h5></a>
                </div>
            </div>
            <div class="flex-grid-footer">
                <div class="col">
                    <a href="https://www.facebook.com/movinggeneral88"><%= image_tag("f_logo_RGB-White_72.png", class: "icon") %></a>
                </div>
                <div class="col">
                    <a href="https://www.instagram.com/movinggeneral88"><%= image_tag("instagram-icon-white.png", class: "icon") %></a>
                </div>
                <div class="col">
                    <a href="https://www.linkedin.com/company/moving-general-llc/"><%= image_tag("In-White-121px-R.png", class: "icon") %></a>
                </div>
            </div>
		    <p class="site-footer__fineprint" id="fineprint">Copyright ©2021 | Moving General LLC | All Rights Reserved</p>
        </div>
    </footer>

</body>
</html>